apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ServiceAccount
metadata:
  name: tomcat-in-the-cloud
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
